### ISSUE TITLE
Warning message: resemble.outputSettings mutates global state

### ISSUE THREAD

**Issue by pablopaul** [codeceptjs/codeceptjs-resemblehelper#44]
I get the following output:

`resemble.outputSettings mutates global state, and will be removed in a later major version`

Can we remove this?

**Comment by puneet0191** [comment]
@Kartikeya99 can you look into this?

**Comment by Kartikeya99** [comment]
I found a similar issue https://github.com/rsmbl/Resemble.js/issues/144#issuecomment-405960445 in the 2nd version of resemblejs and it was promised to be fixed upwards the 3.0.0 version. 
The tool already uses the 3.0.0 version and so I'm assuming that this issue hasn't yet been fixed and will be fixed in either the 4th or later major versions and it should be safe for us to use until the dependency gets updated to a later version.

**Comment by Kartikeya99** [comment]
My pull request removing the warning just got merged at resemblejs. Now we can update the resemblejs dependency and the warning will not come.

**Comment by puneet0191** [comment]
@pablopaul I am closing this issue, if this still happens please feel free to reopen.
